global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'todo-service-otel'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['todo-service:9464']
  
  - job_name: 'todo-service-promclient'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['todo-service:3000']
